# Generated by Django 3.1.6 on 2022-01-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('defense', models.IntegerField()),
                ('icon', models.TextField(verbose_name='/assets/images/shield.png')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='bim bam boom')),
                ('icon', models.TextField(verbose_name='/assets/images/wizard.png')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mana', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('damage', models.IntegerField(default=0)),
                ('icon', models.TextField(verbose_name='/assets/images/sword.png')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('mana', models.IntegerField(default=0)),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.armor')),
                ('character_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.charactertype')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.spell')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.weapon')),
            ],
        ),
    ]
